#!/bin/bash

cd /home/ec2-user

# Install php
yum -y update
yum -y upgrade

cd ~
curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
nano /tmp/nodesource_setup.sh
sudo bash /tmp/nodesource_setup.sh
yum -y install nodejs

yum -y install npm

